# Generated by Django 5.0 on 2024-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tenant_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
    ]
